env: default
namespace: nlalex


ssm:
  patch_baseline:
    amazon_linux2_patch_baseline:
      description: 'custom patch baseline for amazon linux 2'
      operating_system: 'AMAZON_LINUX_2'
      approved_patches_enable_non_security: True
      approve_after_days: 7
      compliance_level: 'CRITICAL'
      enable_non_security: True
      patch_groups:
        - 'custom_test'
      patch_filter_properties:
        PRODUCT:
          values:
            - 'AmazonLinux2'
            - 'AmazonLinux2.0'
        CLASSIFICATION:
          values:
            - 'Security'
            - 'Bugfix'
            - 'Enhancement'
            - 'Recommended'
        SEVERITY:
          values:
            - 'Critical'
            - 'Important'
            - 'Medium'
            - 'Low'
  maintenance_window:
    maintenance_window_1:
      description: 'this is a description'
      allow_unassociated_targets: True
      schedule: 'cron(*/5 * ? * * *)'
      duration: 4
      cutoff: 1
      schedule_timezone: 'America/Denver'
      maintenance_window_target:
        description: 'this is a maintenance window target'
        resource_type: 'INSTANCE'
        name: 'maint_window_target'
        targets:
          - key: 'tag:environment'
            values:
              - 'development'
      maintenance_window_task:
        task_type: 'RUN_COMMAND'
        max_concurrency: '5'
        max_errors: '5'
        priority: 1
        task_arn: 'AWS-RunPatchBaseline'

